/**
 * Docs generator. Inlines every `*.md` in packages/core/src/docs/ into a plain
 * generated.ts string map, so the docs ship in the bundle with no import
 * attributes (`with { type: ... }`) — those trip some TS language servers and
 * aren't recognized for non-json types. Run: bun run gen:docs
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const DOCS_DIR = join(HERE, "..");
const OUT = join(DOCS_DIR, "generated.ts");

function main() {
    const files = readdirSync(DOCS_DIR)
        .filter((f) => f.endsWith(".md"))
        .sort();
    const entries = files.map(
        (f) => `    ${JSON.stringify(f)}: ${JSON.stringify(readFileSync(join(DOCS_DIR, f), "utf8"))},`,
    );
    const body = [
        "// generated by docs/scripts/generate.ts — do not edit by hand",
        "// edit the .md files in docs/ and re-run: bun run gen:docs",
        "export const DOCS_CONTENT: Record<string, string> = {",
        ...entries,
        "};",
        "",
    ].join("\n");
    writeFileSync(OUT, body);
    console.log(`generated ${files.length} doc(s) → ${OUT}`);
}

main();
