/**
 * Catalog generator. Fetches models.dev → emits generated/models.json + models.ts.
 * Run: npm run gen:catalog
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { ModelInfo, ProviderId } from "../../types";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(HERE, "..", "generated");
const SOURCE = "https://models.dev/api.json";
const PROVIDERS: ProviderId[] = ["xai", "anthropic", "openai", "google", "openrouter"];

interface RawModel {
  id?: string;
  name?: string;
  limit?: { context?: number; output?: number };
  cost?: { input?: number; output?: number; cache_read?: number; cache_write?: number };
  reasoning?: boolean;
  modalities?: { input?: string[]; output?: string[] };
}

interface RawProvider {
  models?: Record<string, RawModel>;
}

async function main() {
  const res = await fetch(SOURCE);
  if (!res.ok) throw new Error(`models.dev fetch failed: ${res.status}`);
  const all = (await res.json()) as Record<string, RawProvider>;

  const out: Record<string, ModelInfo> = {};
  for (const provider of PROVIDERS) {
    const models = all[provider]?.models ?? {};
    for (const [rawId, m] of Object.entries(models)) {
      const id = `${provider}/${rawId}`;
      out[id] = {
        id,
        provider,
        name: m.name ?? rawId,
        contextWindow: m.limit?.context ?? 0,
        maxOutput: m.limit?.output ?? 0,
        cost: {
          input: m.cost?.input ?? 0,
          output: m.cost?.output ?? 0,
          cacheRead: m.cost?.cache_read ?? 0,
          cacheWrite: m.cost?.cache_write ?? 0,
        },
        reasoning: m.reasoning ?? false,
        modalities: m.modalities?.input ?? ["text"],
        available: true,
      };
    }
  }

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(join(OUT_DIR, "models.json"), JSON.stringify(out, null, 2));
  writeFileSync(
    join(OUT_DIR, "models.ts"),
    `// generated by catalog/scripts/generate.ts — do not edit by hand\nimport type { ModelInfo } from "../../types";\nimport raw from "./models.json" with { type: "json" };\nexport const GENERATED_MODELS = raw as unknown as Record<string, ModelInfo>;\n`,
  );

  const count = Object.keys(out).length;
  console.log(`generated ${count} models across ${PROVIDERS.length} providers → ${OUT_DIR}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
