#!/usr/bin/env python3
"""Render the Homebrew formula for loop from a release's SHA256SUMS.

Usage:
    render-formula.py <version> <sha256sums-path> <output-path>

Reads the aggregated SHA256SUMS (one "<sha>  loop-<target>.tar.gz" line per
asset) and writes a complete Formula/loop.rb. Each platform block is emitted
only if its tarball is present in SHA256SUMS, so Intel-mac support appears
automatically once the release includes loop-darwin-x64.tar.gz.

Invoked by the update-homebrew-tap job in release.yml — keep the output in sync
with the bootstrap formula committed to notshekhar/homebrew-tap.
"""
import re
import sys

# `#{{version}}` survives str.format as the literal Ruby interpolation `#{version}`.
URL = "https://github.com/notshekhar/loop/releases/download/v#{{version}}/loop-{target}.tar.gz"


def main() -> int:
    if len(sys.argv) != 4:
        sys.exit(f"usage: {sys.argv[0]} <version> <sha256sums> <output>")
    version, sums_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3]

    sums: dict[str, str] = {}
    with open(sums_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            sha, fname = line.split()
            m = re.match(r"loop-(.+)\.tar\.gz$", fname)
            if m:
                sums[m.group(1)] = sha

    if "darwin-arm64" not in sums:
        sys.exit("SHA256SUMS missing darwin-arm64 — refusing to render a broken formula")

    def arch(label: str, target: str) -> str:
        return (
            f"    {label} do\n"
            f'      url "{URL.format(target=target)}"\n'
            f'      sha256 "{sums[target]}"\n'
            f"    end"
        )

    mac = [arch("on_arm", "darwin-arm64")]
    if "darwin-x64" in sums:
        mac.append(arch("on_intel", "darwin-x64"))
    else:
        # No prebuilt Intel-mac binary in this release (darwin-x64 isn't in the
        # CI matrix). Fail the install with a clear pointer rather than letting
        # Homebrew emit a confusing "no available formula" error. odie inside an
        # on_intel block runs only when evaluated on an Intel mac.
        mac.append(
            "    on_intel do\n"
            '      odie <<~EOS\n'
            "        loop has no prebuilt Intel-mac (x86_64) binary yet.\n"
            "        Install it directly instead:\n"
            "          curl -fsSL https://raw.githubusercontent.com/notshekhar/loop/main/install.sh | bash\n"
            "      EOS\n"
            "    end"
        )

    linux = []
    if "linux-arm64" in sums:
        linux.append(arch("on_arm", "linux-arm64"))
    if "linux-x64" in sums:
        linux.append(arch("on_intel", "linux-x64"))

    formula = f"""# typed: false
# frozen_string_literal: true

# loop — terminal coding agent. Multi-provider, fast, native TUI.
#
# AUTO-GENERATED by the update-homebrew-tap job in notshekhar/loop's release.yml
# (.github/scripts/render-formula.py). Do not hand-edit — the next tag overwrites
# any changes to version/sha256. Edit the render script instead.
class Loop < Formula
  desc "Terminal coding agent — multi-provider, fast, native TUI"
  homepage "https://github.com/notshekhar/loop"
  version "{version}"
  license "MIT"

  on_macos do
{chr(10).join(mac)}
  end

  on_linux do
{chr(10).join(linux)}
  end

  def install
    # Tarball layout is <target>/{{loop,package.json}}; Homebrew chdirs into the
    # sole top-level dir. The binary reads its sidecar package.json via
    # dirname(execPath), so keep both together in libexec and symlink onto PATH
    # (execPath resolves through the symlink).
    libexec.install "loop", "package.json"
    bin.install_symlink libexec/"loop"
    bin.install_symlink libexec/"loop" => "agent"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/loop --version")
  end
end
"""

    with open(out_path, "w") as f:
        f.write(formula)
    print(formula)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
