package provider

import "time"

// Content is one item of model output. The concrete types are Text,
// Reasoning, ReasoningFile, File, Source, ToolCall, ToolResult,
// ToolApprovalRequest, and CustomContent.
//
// Every Content type is also a StreamPart, so a streaming provider emits the
// same values a non-streaming one collects.
type Content interface {
	isContent()
	StreamPartType() string
}

// Text is generated text.
type Text struct {
	Text             string
	ProviderMetadata ProviderMetadata
}

// Reasoning is generated reasoning.
type Reasoning struct {
	Text             string
	ProviderMetadata ProviderMetadata
}

// ReasoningFile is a file generated as part of reasoning. Data is
// FileDataBytes or FileDataURL.
type ReasoningFile struct {
	MediaType        string
	Data             FileData
	ProviderMetadata ProviderMetadata
}

// File is a file generated by the model. Data is FileDataBytes or
// FileDataURL, returned in whichever form the provider API used so no
// needless re-encoding happens.
type File struct {
	MediaType        string
	Data             FileData
	ProviderMetadata ProviderMetadata
}

// SourceType distinguishes the kinds of Source.
type SourceType string

const (
	// SourceURL is a web page used to ground the response.
	SourceURL SourceType = "url"
	// SourceDocument is a file or document used to ground the response.
	SourceDocument SourceType = "document"
)

// Source is an input the model cited when generating the response. URL and
// MediaType/Filename are populated according to SourceType.
type Source struct {
	SourceType SourceType
	ID         string

	// URL is set when SourceType is SourceURL.
	URL string
	// MediaType is set when SourceType is SourceDocument.
	MediaType string
	// Filename is optional and only meaningful for SourceDocument.
	Filename string

	Title            string
	ProviderMetadata ProviderMetadata
}

// ToolCall is a tool invocation requested by the model.
//
// Input is the raw JSON string of the arguments, not a decoded object: it is
// reproduced exactly as the provider emitted it so that streamed input deltas
// concatenate to precisely this value.
type ToolCall struct {
	ToolCallID string
	ToolName   string
	Input      string

	// ProviderExecuted reports that the provider ran the tool itself, so the
	// client must not execute it.
	ProviderExecuted bool
	// Dynamic marks a tool defined at runtime, e.g. one bridged from MCP.
	Dynamic bool

	ProviderMetadata ProviderMetadata
}

// ToolResult is the result of a tool the provider executed itself.
type ToolResult struct {
	ToolCallID string
	ToolName   string
	Result     JSONValue

	// IsError reports that Result describes a failure.
	IsError bool
	// Preliminary marks an intermediate result that a later result replaces,
	// such as a progressive image preview. A final result always follows.
	Preliminary bool
	// Dynamic marks a tool defined at runtime.
	Dynamic bool

	ProviderMetadata ProviderMetadata
}

// ToolApprovalRequest asks the caller to approve a provider-executed tool call
// before it runs. Answer it with a ToolApprovalResponsePart.
type ToolApprovalRequest struct {
	ApprovalID       string
	ToolCallID       string
	ProviderMetadata ProviderMetadata
}

// CustomContent is provider-specific output with no standardized payload.
// Kind is formatted "{provider}.{type}".
type CustomContent struct {
	Kind             string
	ProviderMetadata ProviderMetadata
}

func (Text) isContent()                {}
func (Reasoning) isContent()           {}
func (ReasoningFile) isContent()       {}
func (File) isContent()                {}
func (Source) isContent()              {}
func (ToolCall) isContent()            {}
func (ToolResult) isContent()          {}
func (ToolApprovalRequest) isContent() {}
func (CustomContent) isContent()       {}

// FinishReasonKind is the unified, cross-provider reason a generation stopped.
type FinishReasonKind string

const (
	// FinishStop means the model emitted a stop sequence or ran out of things to say.
	FinishStop FinishReasonKind = "stop"
	// FinishLength means the output token limit was reached.
	FinishLength FinishReasonKind = "length"
	// FinishContentFilter means a content filter halted generation.
	FinishContentFilter FinishReasonKind = "content-filter"
	// FinishToolCalls means the model stopped to call tools.
	FinishToolCalls FinishReasonKind = "tool-calls"
	// FinishError means generation stopped because of an error.
	FinishError FinishReasonKind = "error"
	// FinishOther covers anything else.
	FinishOther FinishReasonKind = "other"
)

// FinishReason pairs the unified reason with the provider's original string,
// so callers can branch portably without losing provider detail.
type FinishReason struct {
	Unified FinishReasonKind
	Raw     string
}

// InputTokens breaks down prompt token usage. Every field is optional:
// a nil pointer means the provider did not report that figure, which is
// different from reporting zero.
type InputTokens struct {
	Total      *int64
	NoCache    *int64
	CacheRead  *int64
	CacheWrite *int64
}

// OutputTokens breaks down completion token usage. Nil means not reported.
type OutputTokens struct {
	Total     *int64
	Text      *int64
	Reasoning *int64
}

// Usage is the token accounting for one model call.
type Usage struct {
	InputTokens  InputTokens
	OutputTokens OutputTokens

	// Raw is the provider's usage payload verbatim, including any fields the
	// unified shape has no place for.
	Raw JSONObject
}

// ResponseMetadata identifies a provider response.
type ResponseMetadata struct {
	ID        string
	Timestamp time.Time
	ModelID   string
}
