/**
 * Post-turn recap: a short "what just happened" summary generated by a second
 * cheap generateText pass after each assistant response.
 *
 * The AI SDK has no extra-step hook on streamText for a follow-up generation,
 * so this runs as its own call after the turn ends (same pattern as
 * compaction). The result reaches the UI as a "data-recap" event — named
 * after the AI SDK's `data-*` custom data part convention — and persists as a
 * custom entry so resumed sessions re-render it. It never enters the model's
 * context (messages() only reads "message" entries).
 */
import { generateText } from "ai";
import { getModel } from "../providers";
import type { Session } from "../sessions";
import type { CostTracker } from "./cost";

export const RECAP_KIND = "recap";

/** Shape of the custom entry payload a recap persists as. */
export interface RecapPayload {
    kind: typeof RECAP_KIND;
    text: string;
}

export function isRecapPayload(payload: unknown): payload is RecapPayload {
    const p = payload as RecapPayload | null;
    return !!p && typeof p === "object" && p.kind === RECAP_KIND && typeof p.text === "string";
}

// Only turns that changed files earn a recap — pure Q&A turns don't.
// (Subagent writes happen inside the task tool and don't count here.)
const MUTATING_TOOLS = new Set(["write", "edit"]);

export function turnDeservesRecap(toolsUsed: string[]): boolean {
    return toolsUsed.some((tool) => MUTATING_TOOLS.has(tool));
}

const RECAP_PROMPT = `You write the short recap shown under a coding-agent response.

Rules:
- 2 to 3 short plain-text lines. No bullets, no heading, no quotes, no markdown.
- Past tense, concrete: name the files/commands/decisions that mattered.
- If the turn only answered a question, recap the answer.
- Never invent work that isn't in the input.`;

const MAX_INPUT_CHARS = 12_000;

export async function runRecap(opts: {
    session: Session;
    modelId: string;
    userInput: string;
    assistantText: string;
    /** Tool names called during the turn, in order (dupes fine). */
    toolsUsed: string[];
    tracker?: CostTracker;
    cwd?: string;
    abortSignal?: AbortSignal;
}): Promise<string> {
    const tools = [...new Set(opts.toolsUsed)].join(", ");
    const prompt =
        `User asked:\n${opts.userInput.slice(0, 2000)}\n\n` +
        (tools ? `Tools used: ${tools}\n\n` : "") +
        `Assistant responded:\n${opts.assistantText.slice(-MAX_INPUT_CHARS)}`;

    const model = await getModel(opts.modelId);
    const result = await generateText({
        model,
        system: RECAP_PROMPT,
        prompt,
        abortSignal: opts.abortSignal,
    });
    // Models sometimes pad the recap out — cap it at three lines.
    const text = result.text.trim().split("\n").slice(0, 3).join("\n").trim();
    if (!text) return "";

    if (opts.tracker && result.usage) opts.tracker.add(opts.modelId, result.usage, opts.cwd);
    const payload: RecapPayload = { kind: RECAP_KIND, text };
    await opts.session.append({ type: "custom", ts: Date.now(), payload });
    return text;
}
